# Generated by Django 5.0.6 on 2025-05-20 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestorMoras', '0003_remove_cartera_estudiante_remove_cartera_metodo_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodo_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Status_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_cobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Carnet', models.IntegerField()),
                ('Direccion', models.CharField(max_length=100)),
                ('Telefono', models.IntegerField()),
                ('Correo_electronico', models.EmailField(max_length=254, unique=True)),
                ('Estatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_estudiante', to='GestorMoras.status_estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Cartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monto_pagar', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Fecha_cobro', models.DateField()),
                ('Fecha_pago', models.DateTimeField(null=True)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='GestorMoras.estudiante')),
                ('Metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos', to='GestorMoras.metodo_pago')),
                ('Status_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_pago', to='GestorMoras.status_pago')),
                ('Tipo_cobro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_cobro', to='GestorMoras.tipo_cobro')),
            ],
        ),
    ]
